name = "permissionless-staging"
main = "index.js"
compatibility_date = "2025-06-30"

routes = [
    { pattern = "permissionless.staging.k-f.dev/*", zone_name = "k-f.dev" }
]

[assets]
directory = "./dist"

# --- PRODUCTION environment settings ---
[env.production]
name = "permissionless-production"
routes = [
    { pattern = "permissionless.k-f.dev/*", zone_name = "k-f.dev" }
]