main = "index.js"
compatibility_date = "2025-06-30"

[observability]
enabled = true

[assets]
directory = "./dist"

[env.demo]
name = "launchpad-demo"
routes = [
    { pattern = "launchpad-demo.k-f.dev/*", zone_name = "k-f.dev" }
]

[env.staging]
name = "launchpad-staging"
routes = [
    { pattern = "launchpad-staging.k-f.dev/*", zone_name = "k-f.dev" }
]

[env.production]
name = "launchpad-production"
routes = [
    { pattern = "launchpad.k-f.dev/*", zone_name = "k-f.dev" }
]