name = "launchpad-staging"
main = "index.js"
compatibility_date = "2025-06-15"

routes = [
    { pattern = "launchpad-staging.k-f.dev/*", zone_name = "k-f.dev" }
]

[observability]
enabled = true

[assets]
not_found_handling = "single-page-application"
binding = "ASSETS"

# --- PRODUCTION environment settings ---
[env.production]
name = "launchpad-production"
routes = [
    { pattern = "launchpad.k-f.dev/*", zone_name = "k-f.dev" }
]