name = "launchpad-staging"
main = "index.js"
compatibility_date = "2025-07-15"

[assets]
directory = "./dist/client"

routes = [
    { pattern = "launchpad-staging.k-f.dev/*", zone_name = "k-f.dev" }
]

[env.production]
name = "launchpad-production"
routes = [
    { pattern = "launchpad.k-f.dev/*", zone_name = "k-f.dev" }
]