# Default environment is STAGING
name = "launchpad-staging"
main = "dist/"
compatibility_date = "2025-06-30"

routes = [
	{ pattern = "launchpad.staging.k-f.dev/*", zone_name = "k-f.dev" }
]

[assets]
directory = "./dist/client"

# PRODUCTION environment settings
[env.production]
name = "launchpad-production"
routes = [
	{ pattern = "launchpad.k-f.dev/*", zone_name = "k-f.dev" }
]