name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [permissionless, launchpad]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build for Staging
        run: pnpm --filter=${{ matrix.app }} build --mode testnet

      - name: Upload Staging Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}-build
          path: ./apps/${{ matrix.app }}/dist

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [permissionless, launchpad]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install --global wrangler

      - name: Download Staging Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.app }}-build
          path: ./apps/${{ matrix.app }}/dist

      - name: Clean Stale Wrangler Config
        run: rm -rf apps/${{ matrix.app }}/.wrangler

      - name: Deploy to Cloudflare Staging
        run: |
          cd apps/${{ matrix.app }}
          CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }} wrangler deploy
