name: 💬 Comment Cloudflare Preview URLs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment-previews:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait 30s for Pages build to kick off
        run: sleep 30

      - name: Get Launchpad preview URL
        id: launchpad
        uses: zentered/cloudflare-preview-url@v1.4.2
        with:
          cloudflare_project_id: launchpad
          branch: ${{ github.event.pull_request.head.ref }}
          wait_until_ready: true
          timeout: 120

      - name: Get Permissionless preview URL
        id: permissionless
        uses: zentered/cloudflare-preview-url@v1.4.2
        with:
          cloudflare_project_id: permissionless
          branch: ${{ github.event.pull_request.head.ref }}
          wait_until_ready: true
          timeout: 120

      - name: Comment PR with preview URLs
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 **Launchpad preview**: https://${{ steps.launchpad.outputs.preview_url }}
            🚀 **Permissionless preview**: https://${{ steps.permissionless.outputs.preview_url }}
